import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import Header from "./_components/header";
import ClientParticlesWrapper from "./_components/clientParticlesWrapper";
import XMenu from "./_components/menu";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="relative min-h-screen w-full bg-[#1c1c1d] text-white overflow-hidden flex justify-center items-center">
      <div className="absolute inset-0 z-0">
        <ClientParticlesWrapper />
      </div>
      <Header />
        <XMenu/>
        {children}
      
    </div>
  );
}
